name: Update README on file changes

# Triggers
on:
  push: 
    paths:
      - '**' # watch all file 
    
    branches: 
      - main

permissions:
  contents: write

jobs:
  update-readme:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Install tree command
        run: sudo apt-get install tree
      
      - name: Detect structural changes (added, deleted, moved)
        id: structure-check
        run: |
          echo "Checking for file structural changes..."

          # Get structural changes (Added, Deleted, Renamed)
          STRUCTURAL_CHANGES=$(git diff --name-status HEAD~1 | grep -E '^(A|D|R)' || true)

          echo "Detected changes:"
          echo "$STRUCTURAL_CHANGES"

          # Set output for conditionally running next steps
          if [ -n "$STRUCTURAL_CHANGES" ]; then
            echo "structure_changed=true" >> "$GITHUB_OUTPUT"
          else
            echo "structure_changed=false" >> "$GITHUB_OUTPUT"
          fi

      - name: Generate Directory tree
        if: steps.structure-check.outputs.structure_changed == 'true'
        run: |
          tree -L 2 -I 'node_modules|.git|dist' | head -n -1 > structure.txt 
      
      - name: Update README.md
        if: steps.structure-check.outputs.structure_changed == 'true'
        run: |
          START='<!-- TREE START HERE -->'
          END='<!-- TREE ENDS HERE -->'
          CONTENT=$(cat structure.txt)

          awk -v start="$START" -v end="$END" -v content="$CONTENT" '
            BEGIN { replaced = 0 }
            $0 ~ start && !replaced {
              print $0
              print "```"
              print content
              print "```"
              skip = 1
              next
            }
            $0 ~ end && skip {
              print $0
              skip = 0
              replaced = 1
              next
            }
            !skip
          ' README.md > README.tmp && mv README.tmp README.md
      
      - name: Commit and push
        if: steps.structure-check.outputs.structure_changed == 'true'
        run: |
          git config --global user.name 'github-actions[bot]'
          git config --global user.email 'github-actions[bot]@users.noreply.github.com'
          git add README.md
          git commit -m "chore: updated README tree [skip ci]" || echo "No changes"
          git push